apiVersion: v1
kind: Namespace
metadata:
  name: personal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agsimfzi
  namespace: personal
  labels:
    app: agsimfzi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agsimfzi
  template:
    metadata:
      labels:
        app: agsimfzi
    spec:
      containers:
        - name: agsimfzi
          image: 192.168.1.4:5000/agsimfzi:latest
          imagePullPolicy: Always
          ports:
            - name: agsimfzi
              containerPort: 9000
          livenessProbe:
            httpGet:
              path: /
              port: agsimfzi
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: agsimfzi
            failureThreshold: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: agsimfzi
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: agsimfzi
  namespace: personal
spec:
  selector:
    app: agsimfzi
  type: LoadBalancer
  ports:
    - name: agsimfzi-port
      protocol: TCP
      port: 80
      targetPort: agsimfzi
